check inja template syntax in test runner
This is a regression test for 2bb9806. Example output:

    ===============================================================================
    ../testrunner.cc:149:
    TEST CASE:  Inja template syntax
      partials/zaak.html

    ../testrunner.cc:157: ERROR: CHECK_NOTHROW( env.parse_template(entry.path()) ) THREW exception: "[inja.exception.parser_error] (at 3:39) unexpected '}'"

    ===============================================================================